### ISSUE TITLE
Upgrade Flyway to version 9

### ISSUE THREAD

**Issue by yulian-tw** [ThoughtWorks-SEA/recce#288]
**Context / Goal**

Our example MariaDB is of later version than supported version in our Flyway version 8. Version 9 is released in July, but there is numerous bug fixes. Release 9.4 has been around 2 months.
![Screenshot 2022-11-10 at 12 10 51 PM](https://user-images.githubusercontent.com/87641310/201000072-77fbe1b3-4f45-4cf4-8d07-56c9a63dd95e.png)

**Expected Outcome**

- Checkout the [Flyway release notes](https://flywaydb.org/documentation/learnmore/releaseNotes) and attempt to upgrade Flyway. Document if any regression. 

**Out of Scope**

**Additional context / implementation notes**

**Comment by chadlwilson** [comment]
Flyway are pretty conservative about these warnings in my experience, in terms of not "assuming" forwards compatibility with minor MariaDB releases. Suspect maybe they are trying to push people forward that pay for the commercial offerings. It's most likely fine despite the warnings.

In any case, we can do so for the source/target DBs. Only consideration is that Micronaut is still based around Flyway 8, which is used for the Flyway runs that are done for Postgres built into Recce. Not that big a deal to have these deviate though.

**Comment by chadlwilson** [comment]
In general, for the source/target DB examples if I could find/think of a lightweight approach tool to apply sets of SQL to a DB other than Flyway I'd have been totally happy to go with that.

**Comment by chadlwilson** [comment]
Even latest version says `WARNING: Flyway upgrade recommended: MariaDB 10.9 is newer than this version of Flyway and support has not been tested. The latest supported version of MariaDB is 10.6` :-) But upgraded anyway.

**Comment by yulian-tw** [comment]
Thanks for sharing. I'm haven't explore Micronaut, am not aware of Micronaut is still based around Flyway 8. 😅

**Comment by chadlwilson** [comment]
"Opinionated dependency" frameworks like Micronaut and Spring Boot tend to be pretty conservative about incorporating major version updates for dependencies, even if they aren't particularly "breaking". At the moment it comes from [this bill-of-materials](https://mvnrepository.com/artifact/io.micronaut.flyway/micronaut-flyway-bom/5.4.1) (`8.5.13` at time of writing).
